kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: my-azurefile
provisioner: file.csi.azure.com
allowVolumeExpansion: true
mountOptions:
  - nconnect=4
  - noresvport
  - actimeo=30
  - rsize=1048576
  - wsize=1048576
parameters:
  skuName: Premium_LRS
  protocol: nfs
