kind: Pod
apiVersion: v1
metadata:
  name: kaniko
spec:
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:debug
      envFrom:
        - secretRef:
            name: kaniko-secret
      command:
        - /busybox/cat
      tty: true
      volumeMounts:
        - name: docker-config
          mountPath: /kaniko/.docker/
        - name: go-cache
          mountPath: /go/pkg/mod
        - name: go-cache
          mountPath: /.cache
  restartPolicy: Never
  volumes:
    - name: docker-config
      configMap:
        name: docker-config
    - name: go-cache
      persistentVolumeClaim:
        claimName: my-azurefile
